async function verify() {
    enableLoading()

    try {
        const verifyRequest = await fetch("https://api.danielle-and-callum.quintondev.com/v1/auth/verify", {
            method: "POST",
            credentials: "include",
            headers: { "Content-Type": "application/json" }
        })

        if (verifyRequest.status === 200) {
            disableLoading()
            return
        }

        if (verifyRequest.status === 401) {
            window.location.href = "./login.html"
            return
        }

        console.error("Authentication verification failed:", verifyRequest.status)
        window.location.href = "./login.html"
    } catch (err) {
        console.error("Authentication verification failed:", err)
        window.location.href = "./login.html"
    }
}

async function exportToPDF() {
    enableLoading()

    try {
        const dataRequest = await fetch("https://api.danielle-and-callum.quintondev.com/v1/data", {
            method: "POST",
            credentials: "include",
            headers: { "Content-Type": "application/json" }
        })

        if (dataRequest.status === 401) {
            window.location.href = "./login.html"
            return
        }

        if (!dataRequest.ok) {
            console.error("Failed to retrieve guest data:", dataRequest.status)
            return
        }

        const jsonData = await dataRequest.json()

        if (jsonData.status !== true || !Array.isArray(jsonData.data)) {
            console.error("API returned an invalid data response:", jsonData)
            return
        }

        // report.html is opened in the same tab so its sessionStorage is guaranteed
        // to contain the payload generated by this dashboard.
        sessionStorage.setItem("weddingGuestReportData", JSON.stringify(jsonData.data))
        window.location.href = "./report.html"
    } catch (err) {
        console.error("Guest data request failed:", err)
    } finally {
        disableLoading()
    }
}

function enableLoading() {
    const loading = document.getElementById("dashboardSpinner")
    const content = document.getElementById("dashboardContent")
    const header = document.getElementsByTagName("header")[0]
    const footer = document.getElementsByTagName("footer")[0]

    if (content) content.style.display = "none"
    if (header) header.style.display = "none"
    if (footer) footer.style.display = "none"
    if (loading) loading.style.display = "flex"
}

function disableLoading() {
    const loading = document.getElementById("dashboardSpinner")
    const content = document.getElementById("dashboardContent")
    const header = document.getElementsByTagName("header")[0]
    const footer = document.getElementsByTagName("footer")[0]

    if (loading) loading.style.display = "none"
    if (content) content.style.display = "flex"
    if (header) header.style.display = "flex"
    if (footer) footer.style.display = "flex"
}

const exportToPDFbtn = document.getElementById("exportToPDFbtn")
exportToPDFbtn?.addEventListener("click", exportToPDF)

verify()
